name: CI Pipeline

on:
  push:
    branches: [ main, development, release ]
  pull_request:
    branches: [ main, development, release ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода из репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск тестов
        run: |
          export PYTHONPATH=./
          pytest -v

      - name: Обновление документации
        run: |
          echo "CI успешно выполнен: $(date)" >> docs/README.md
          echo "" >> docs/README.md

      - name: Commit обновлённой документации обратно в репозиторий
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@example.com"
          git add docs/README.md
          git commit -m "docs: автообновление README.md через CI" || echo "Нечего коммитить"
          git push origin ${{ github.ref }}
